### ISSUE TITLE
aapt is not available

### ISSUE THREAD

**Issue by lin7sh** [ayufan-pine64/local_manifests#1]
Hi ayufan,

firstly, thank for your work for the pine64 community, you are the only provider who has been doing the hard work. I was trying tho follow your guide to build version 7.1 on my mac, but I got some errors, if the problem is lacking aapt, I couldn't use apt to install it, since I'm using Mac.

```
lunch tulip_chiphd-eng
find: -executable: unknown primary or operator
vendor/google/build/config.mk:20: *** aapt is not available. Please install it first ("sudo apt-get install aapt") or define GAPPS_FORCE_MATCHING_DPI := true.  Stop.

** Don't have a product spec for: 'tulip_chiphd'
** Do you have the right repo manifest?
```

```
$ lunch tulip_chiphd_atv-eng
find: -executable: unknown primary or operator
vendor/google/build/config.mk:20: *** aapt is not available. Please install it first ("sudo apt-get install aapt") or define GAPPS_FORCE_MATCHING_DPI := true.  Stop.

** Don't have a product spec for: 'tulip_chiphd_atv'
** Do you have the right repo manifest?
```

**Comment by lbdroid** [comment]
That failure is actually in a different project -- opengapps.

https://github.com/opengapps/aosp_build/blob/master/config.mk#L20

**Comment by ayufan** [comment]
Hmm, I think that you have to install it then :)

**Comment by lin7sh** [comment]
@ayufan @lbdroid thank you I'll give it a try
